### ISSUE TITLE
Build the project fail 

### ISSUE THREAD

**Issue by xiaoquisme** [SilentCC/JIEba-netcore2.0#1]
I just clone this project  and open with my VS 2017 ,then I build this project and failed 。
the detail is 
`
    <ProjectReference Include="..\..\PanGu.Core\PanGu.Core.csproj" /> 
    <ProjectReference Include="..\..\Lucene.Net\Lucene.Net.csproj" /> 
    <ProjectReference Include="..\..\Lucene.Net.Analysis.Common\Lucene.Net.Analysis.Common.csproj" />
` 
not found

**Comment by SilentCC** [comment]
I fix this bug. Thank you for your help. And the usage is in the new Project Test.

**Comment by xiaoquisme** [comment]
👍 yes !
